config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/items/user', to: 'items#get_items_by_user', as: 'user_items'
  post "/items/:id/comment", to: "comments#create", as: 'create_comment'
  get '/items/category/:category', to: 'items#search_by_category', as: 'search_category'
  get '/users/items', to: 'items#get_items_by_user', as: 'search_user_items'
  get '/search', to: 'items#search', as: 'search'
  resources :items
  resources :users
  resources :new
  resources :wishlists

  get '/wishlists/:id/add', to: 'wishlists#create', as: 'add_wishlists'
  delete '/wishlists/:id/delete', to: 'wishlists#destroy', as: 'delete_wish'

  get '/myitems', to: 'wishlists#myitems', as: 'myitems'
  

  get '/register', to: 'users#index', as: 'register'
  post 'sessions/create'
  get '/login', to: 'sessions#new', as: 'login_path'
  post '/login', to: 'sessions#create'
  get "/logout" => "users#logout", :as => "logout"
  get "/users/:id", to: "users#show", as: "profile"
  get "/users/:id/reset", to: "users#reset", as: "reset_password"
  get '/auth/:provider/callback' => 'sessions#omniauth'

  
  root :to => redirect('/items')
end

app/models/item.rb
class Item < ActiveRecord::Base
    has_many :wishlists
    has_many :comments
    belongs_to :user
    has_many_attached :images
    
    validates :title, :presence=> true
    validates :price, :presence=> true

    def Item.search_by_category(category)
        if category.nil?
            return []
        end
        return Item.where(category: category)
    end

    def Item.search(term)
      if term.nil?
        return []
      end
      return Item.where("lower(title) LIKE :search OR lower(category) LIKE :search OR lower(description) LIKE :search", search: "%#{term}%").uniq
    end

    def Item.search_by_user(user_id)
        return Item.where(user_id: user_id)
    end

    def Item.get_all_category()
        return ['Clothing', 'Shoes', 'Jewelry & Watches', 
            'Electronics', 'Home & Tools', 'Beauty & Health', 
            'Sports', 'Books', 'Pets', 'Grocery', 'Others']
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :check_login, except: %i[index]
  before_action :check_user_accessibility, only: %i[ edit update destroy ]

  #check log in
  def check_login
    @current_user = session[:user_id]
    if @current_user == nil
      return redirect_to(login_path)
    end
    @user = User.find(session[:user_id])
  end

  def check_user_accessibility
    if @current_user != @item.user_id
      flash[:notice] = "You are not authorized to edit this item"
      return redirect_to items_path
    end
  end

  # GET /items or /items.json
  def index
    id = session[:user_id]
    if id != nil
      @user = User.find(session[:user_id])
    end

    # @user = User.find(session[:user_id])
    category = params[:category]
    @items = Item.search_by_category(category)
    if @items.empty?
      @items = Item.all
    end
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find params[:id]
    comments = Comment.search_comments_by_item_id(params[:id])
    @comments = []
    comments.each do |c|
      username = User.find(c.user_id).name
      time = c.created_at
      description = c.description
      comment_id = c.id
      @comments.append({id: comment_id, username: username, time: time, description: description})
    end
  end

  # GET /items/new
  def new
    @item = Item.new
    @category_list = Item.get_all_category()
  end

  # GET /items/1/edit
  def edit
    @item = Item.find_by_id params[:id]
    @category_list = Item.get_all_category()
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = @current_user
    
    if @item.save
      flash[:notice] = "#{@item.title} was successfully created"
      redirect_to item_path(@item)
    else
      flash[:notice] = @item.errors.full_messages[0]
      @category_list = Item.get_all_category()
      render 'new', :status=>422
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    @item = Item.find params[:id]
    @item.images.purge
    if @item.update(item_params)
      flash[:notice] = "#{@item.title} was successfully updated."
      redirect_to item_path(@item)
    else
      render 'edit', :status=>422
    end

  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item = Item.find_by_id params[:id]
    @item.images.purge
    @item.destroy
    flash[:notice] = "Item '#{@item.title}' has been deleted"
    redirect_to items_path
  end

  # GET /items/category/:category
  def search_by_category
    cat = params[:category]
    @items = Item.search_by_category(cat)

    if @items.length > 0
      render 'index'
    else
      flash[:notice] = "Nothing found under this category"
      return redirect_to items_path
    end
  end

  #GET /search/:search_term
  def search
    term = params[:search_term].first.downcase
    @items = Item.search(term)
    if @items.length > 0
      params[:search_term] = ''
      render 'index'
    else
      flash[:notice] = "Nothing found under this keyword"
      return redirect_to items_path
    end
  end

  def get_items_by_user
    @items = Item.search_by_user @current_user
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :category, :price, :number, :search_term, images: [])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<!DOCTYPE html>
<html>
  <body>
    <main class="container">
      <div class="pt-5 text-center">
        <h2>Edit Your Item</h2>
        <p class="lead">Please fill in the blank below to edit your product.</p>
      </div>
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <hr class="mb-4">
          <%= form_for (@item), class: 'form-horizontal' do |f| %>
            <%= f.label :title, 'Title', class: 'col-form-label' %>
            <%= f.text_field :title, class: 'form-control mb-3' %>

            <%= f.label :description, 'Description', class: 'col-form-label' %>
            <%= f.text_field :description, class: 'form-control mb-3' %>

            <%= f.label  :category, 'Category', class: 'col-form-label' %>
            <%= f.select  :category, @category_list, {}, {class: 'form-control mb-3'} %>

            <%= f.label :price, 'Price', class: 'col-form-label' %>
            <%= f.text_field :price, class: 'form-control mb-3' %>

            <%= f.label :number, 'Number', class: 'col-form-label' %>
            <%= f.text_field :number, class: 'form-control mb-3' %>

            <%= f.label  :images, "Image", class: 'col-form-label' %>
            <%= f.file_field  :images, multiple: true, direct_upload: true %>

            <div class='row mb-3'>
              <div class='col text-center'>
                <%= submit_tag 'Save Changes', class: 'btn btn-primary mr-3 ml-5' %>
                <%= link_to 'Cancel', items_path, class: 'btn btn-secondary' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/items/index.html.erb
<!--
<h1 class="h1">Items</h1>


<div class="card-deck">
<% @items.each do |item| %>
    <div class="card border-dark mb-3" style="max-width: 18rem;">
        <div class="card-header"><%= item.title%></div>
        <div class="card-body text-dark">
            <p class="card-text"> <%= item.description %> </p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Price: $<%= item.price %> </li>
        </ul>
        <div class="card-body">
            <%= link_to "Detail", item_path(item), class: "card-link" %>
            <%= link_to "Category", items_path(category: item.category), class: "card-link" %>
            <%= link_to "Contact", items_path, class: "card-link" %>
        </div>
    </div>

<% end %>

</div>
-->


<!doctype html>
<html>
  <body>
    <main>
      <div class="album py-5">
        <div class="container">

          <div class="row">
            <div class="card-columns">
            <% @items.reverse_each do |item| %>
              <div class="card mb-4 box-shadow">
                <a class="card-block stretched-link text-decoration-none" href=<%= item_path(item)%>>
                  <%# <img class="card-img-top" data-src="./iphone.jpeg" alt="Card image cap"> %>
                  <% if item.images.attached? %>
                    <%= image_tag item.images[0], :class=>'card-img-top' %>
                  <% end %>
                  <div class="card-header text-dark"><strong><%= item.title %></strong></div>
                  <div class="card-body">
                    <p class="card-text lead text-dark"><small>$<%= item.price %></small></p>
                    <p class="card-text text-secondary"><%= item.description %></p>
                    <p class="card-text"><small class="text-muted"><%= item.updated_at %></small></p>
                  </div>
                </a>
              </div>
            <% end %>
            </div>
          </div>

        </div>
      </div>
    </main>
  </body>
</html>

app/views/items/new.html.erb
<!DOCTYPE html>
<html>
  <body>
    <main class="container">
      <div class="pt-5 text-center">
        <h2>Post Your Item</h2>
        <p class="lead">Please fill in the blank below to post your product.</p>
      </div>
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <hr class="mb-4">
          <%= form_for (@item), class: 'form-horizontal' do |f| %>
            <%= f.label :title, 'Title', class: 'col-form-label' %>
            <%= f.text_field  :title, class: 'form-control mb-3' %>

            <%= f.label  :description, 'Description', class: 'col-form-label' %>
            <%= f.text_field  :description, class: 'form-control mb-3' %>

            <%= f.label  :category, 'Category', class: 'col-form-label' %>
            <%= f.select  :category, @category_list, {}, {class: 'form-control mb-3'} %>

            <%= f.label  :price, 'Price', class: 'col-form-label' %>
            <%= f.text_field  :price, class: 'form-control mb-3' %>

            <%= f.label  :number, 'Number', class: 'col-form-label' %>
            <%= f.text_field  :number, class: 'form-control mb-3' %> 

            <%= f.label  :images, "Image", class: 'col-form-label' %>
            <%= f.file_field  :images, multiple: true, direct_upload: true %>

            <div class='row mb-3'>
              <div class='col text-center'>
                <%= submit_tag 'Post', class: 'btn btn-primary mr-3 ml-5' %>
                <%= link_to 'Cancel', items_path, class: 'btn btn-secondary' %>
              </div>
            </div> 
          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/items/show.html.erb
<!DOCTYPE html>
<html>
  <body>
    <main class="container">
      <div class="row">
        <div class="col-6 offset-md-1">
          <div id="carouselExampleIndicators" class="carousel slide mt-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <% for i in 1...@item.images.length() %>
                <li data-target="#carouselExampleIndicators" data-slide-to="<%=i%>"></li>
              <% end %>
            </ol>
            <div class="carousel-inner">
              <% for i in (0...@item.images.length()) do %>    
                <div class="carousel-item <%= i == 0 ? 'active' : '' %>">
                  <%= image_tag @item.images[i], class: 'd-block w-100' %>
                </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>

        <div class="col-5 pl-5">
          <h1 class="mt-4"><%= @item.title %></h1>
          <%= link_to @item.category, search_category_path(:category=>@item.category), class: 'blockquote-footer' %>
          <p class='lead'>$<%= @item.price %></p>
          <h4>Description:</h4>
          <p id="description">
            <%= @item.description %>
          </p>
          <% if @item.user_id != @current_user %>
            <h4>Contact with Seller:</h4>
            <p class='blockquote-footer'><em>Have questions? Comment first!</em></p>
            <div class="row pl-2">
              <%= link_to "Contact", profile_path(@item.user_id), class: 'btn btn-primary m-1' %>
            </div>
          <% end %>
          
          <p class='text-muted'>
            <small>Updated at <%= @item.updated_at %></small>
          </p>
          <div class="row pl-2">
            <% if @item.user_id != @current_user %>
              <% if session[:user_id] && Wishlist.find_by(user_id: session[:user_id], item_id: @item.id) %>
                <%= button_to "Remove from Wishlist", delete_wish_path, method: :delete,  class: 'btn btn-primary m-1' %>
              <% else%>
                <%= link_to 'Add to Wishlist', add_wishlists_path, class: 'btn btn-primary m-1' %>
              <% end %>
            <% end %>
            <% if !(@item.category.nil? or @item.category.empty?) %>
              <%= link_to "Show Category", search_category_path(:category=>@item.category), class: 'btn btn-primary m-1' %>
            <% end %>
          </div>
          <% if @item.user_id == @current_user %>
            <div class="row pl-2">
              <%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-secondary m-1' %>
              <%= button_to "Delete", item_path(@item), method: :delete, form:{ data: { turbo_method: :delete}}, class: 'btn btn-secondary m-1' %>  
            </div>
          <% end %>
        </div>
      </div>
      <br>
      <hr/>
      <br>
      <div class="row d-flex mb-5">
        <div class="col-md-10 offset-md-1">
          <h2 class="mb-3">Comment</h2>
          <%= form_with(url: create_comment_path(@item.id), method: :post, :class=>"form-inline pb-5") do |f| %>
            <%= f.text_field :description, :class=> "form-control flex-fill", :placeholder=>"Leave your comment..." %>
            <%= f.submit 'Post', :class => 'btn btn-outline-primary ml-2' %>
          <% end %>

          <% if @comments.length == 0 %>
              <p class="text-center"> - Leave the first comment! - </p>
          <% end %>
          <% @comments.each do |comment|%>
            <div class="card mb-4">
              <div class="card-body">
                <p><%= comment[:description] %></p>

                <div class="d-flex justify-content-between">
                  <div class="d-flex flex-row align-items-center">
                    <img src="https://cdn-icons-png.flaticon.com/512/2102/2102647.png" alt="avatar" width="21"
                      height="21" />
                    <p class="small mb-0 ms-2 ml-2"><%= comment[:username] %></p>
                  </div>
                  <div class="d-flex flex-row align-items-center">
                    <p class="small text-muted mb-0"><%= comment[:time] %></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>