config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/items/user', to: 'items#get_items_by_user', as: 'user_items'
  post "/items/:id/comment", to: "comments#create", as: 'create_comment'
  get '/items/category/:category', to: 'items#search_by_category', as: 'search_category'
  get '/users/items', to: 'items#get_items_by_user', as: 'search_user_items'
  get '/search', to: 'items#search', as: 'search'
  resources :items
  resources :users
  resources :new
  resources :wishlists

  get '/wishlists/:id/add', to: 'wishlists#create', as: 'add_wishlists'
  delete '/wishlists/:id/delete', to: 'wishlists#destroy', as: 'delete_wish'

  get '/myitems', to: 'wishlists#myitems', as: 'myitems'
  

  get '/register', to: 'users#index', as: 'register'
  post 'sessions/create'
  get '/login', to: 'sessions#new', as: 'login_path'
  post '/login', to: 'sessions#create'
  get "/logout" => "users#logout", :as => "logout"
  get "/users/:id", to: "users#show", as: "profile"
  get "/users/:id/reset", to: "users#reset", as: "reset_password"
  get '/auth/:provider/callback' => 'sessions#omniauth'

  
  root :to => redirect('/items')
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartassFirstIter</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href=<%= items_path%>>Smart-Ass</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Category
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%# <a class="dropdown-item" href="/items/IT">IT</a>
                <a class="dropdown-item" href="#">Furniture</a> %>
                <%= link_to "Shoes", search_category_path("Shoes"), class: 'dropdown-item' %>
                <%= link_to "Clothing", search_category_path("Clothing"), class: 'dropdown-item' %>
                <%= link_to "Jewelry & Watches", search_category_path("Jewelry & Watches"), class: 'dropdown-item' %>
                <%= link_to "Electronics", search_category_path("Electronics"), class: 'dropdown-item' %>
                <%= link_to "Home & Tools", search_category_path("Home & Tools"), class: 'dropdown-item' %>
                <%= link_to "Beauty & Health", search_category_path("Beauty & Health"), class: 'dropdown-item' %>
                <%= link_to "Sports", search_category_path("Sports"), class: 'dropdown-item' %>
                <%= link_to "Books", search_category_path("Books"), class: 'dropdown-item' %>
                <%= link_to "Pets", search_category_path("Pets"), class: 'dropdown-item' %>
                <%= link_to "Grocery", search_category_path("Grocery"), class: 'dropdown-item' %>
                <%= link_to "Others", search_category_path("Others"), class: 'dropdown-item' %>
                
              </div>
            </li>
            <li class="nav-item active">
              <%= link_to 'Post', new_item_path, class: "nav-link" %>
            </li>
            
            <%= form_tag search_path, :method=>"get", class: 'form-inline my-2 my-lg-0 ml-3' do %>
              <%= text_field :search_term, params[:search_term], class:'form-control mr-sm-2' %>
              <%= button_tag "Search", class: 'btn btn-outline-success my-2 my-sm-0' %>
            <% end %>
            
          </ul>


          <div class="d-flex align-items-center">
            
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if session[:user_id] %>
              <%= link_to "Profile", profile_path(@user.id), class: 'btn btn-link px-3 me-2' %>
              <%= link_to "Wishlist", wishlists_path, class: 'btn btn-link px-3 me-2' %>
              <%= link_to "My Items", myitems_path, class: 'btn btn-link px-3 me-2' %>
              <%= link_to "Logout", logout_path, class: 'btn btn-link px-3 me-2' %>
              <% else  %>
              <%= link_to 'Login', login_path, class: 'btn btn-link px-3 me-2' %>
              <%= link_to 'Sign up', register_path, class: 'btn btn-link px-3 me-2' %>
              <% end %>
                <%# <a class="dropdown-item" href="#">IT</a>
                <a class="dropdown-item" href="#">Furniture</a>
                <a class="dropdown-item" href="#">Vehicle</a> %>
              </div>
            </div>
          </div>
          
        </div>
      </nav>
    </header>

    <div class="container">
    <br>
    <%= render 'layouts/flash' %>
    <%= yield %>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>